apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: "Server=sqlserver-payment,1433;Database=fiapgames_payment;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5"
